apiVersion: v1
kind: Service
metadata:
  name: physical-core
  namespace: physical-health
spec:
  type: ClusterIP
  selector:
    app: physical-core
  ports:
    - name: http
      port: 9001
      targetPort: 9001
