---
apiVersion: v1
kind: Service
metadata:
  name: price-svc
  namespace: ilbuy-l5
  labels:
    app: price-svc
    layer: l5
spec:
  type: ClusterIP
  selector:
    app: price-svc
  ports:
    - port: 8033
      targetPort: 8033
      name: http

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: price-svc
  namespace: ilbuy-l5
