apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus-ilbuy
    access: proxy
    url: http://prometheus.ilbuy-ops.svc.cluster.local:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: POST

  - name: Loki
    type: loki
    uid: loki-ilbuy
    access: proxy
    url: http://loki.ilbuy-ops.svc.cluster.local:3100
    editable: false

  - name: Jaeger
    type: jaeger
    uid: jaeger-ilbuy
    access: proxy
    url: http://jaeger-query.ilbuy-ops.svc.cluster.local:16686
    editable: false
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki-ilbuy
        spanStartTimeShift: -1h
        spanEndTimeShift: 1h
