FROM eclipse-temurin:11.0.25-jre-focal

RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
WORKDIR /app
RUN mkdir -p /app/logs

ENV JAVA_OPTS="-Xms512m -Xmx1g -XX:+UseG1GC -Djava.security.egd=file:/dev/./urandom"

COPY microservices/physical-core/target/physical-core-1.0.0.jar app.jar

EXPOSE 9001

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar app.jar"]
