server:
  port: 8082

spring:
  application:
    name: ilbuy-business-logic

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.ilbuy: DEBUG
