---
apiVersion: v1
kind: Service
metadata:
  name: supplier-svc
  namespace: ilbuy-l5
  labels:
    app: supplier-svc
    layer: l5
spec:
  type: ClusterIP
  selector:
    app: supplier-svc
  ports:
    - port: 8030
      targetPort: 8030
      name: http

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: supplier-svc
  namespace: ilbuy-l5
