apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: physical-dr-hpa
  namespace: physical-health
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: physical-dr
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
