apiVersion: v1
kind: Service
metadata:
  name: physical-dr
  namespace: physical-health
  labels:
    app: physical-dr
spec:
  type: ClusterIP
  selector:
    app: physical-dr
  ports:
    - name: http
      port: 9011
      targetPort: 9011
