apiVersion: v1
kind: Service
metadata:
  name: decision-svc
  labels:
    app: decision-svc
spec:
  selector:
    app: decision-svc
  ports:
    - protocol: TCP
      port: 8012
      targetPort: 8012
  type: ClusterIP
