apiVersion: v1
kind: Service
metadata:
  name: decision-svc
  namespace: ilbuy-l2
  labels:
    app: decision-svc
    tier: l2-ai
    component: decision-hub
spec:
  type: ClusterIP
  selector:
    app: decision-svc
  ports:
    - name: http
      protocol: TCP
      port: 8012
      targetPort: 8012
