apiVersion: v1
kind: Service
metadata:
  name: user-profile-svc
  namespace: ilbuy-prod
  labels:
    app: user-profile-svc
    layer: l0-user-input
  annotations:
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  selector:
    app: user-profile-svc
  ports:
    - name: http
      protocol: TCP
      port: 8001
      targetPort: 8001
