---
apiVersion: v1
kind: Service
metadata:
  name: report-svc
  namespace: ilbuy-l5
  labels:
    app: report-svc
    layer: l5
spec:
  type: ClusterIP
  selector:
    app: report-svc
  ports:
    - port: 8024
      targetPort: 8024
      name: http

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: report-svc
  namespace: ilbuy-l5
