apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-svc-config
  namespace: ilbuy-l5
  labels:
    app: cart-svc
    layer: l5
    env: production
# prod replicas_hint: 2
data:
  ENV: "production"
  GIN_MODE: "release"
  SERVER_PORT: "8025"
  REDIS_HOST: "redis.ilbuy-infra.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_DB: "5"
  CART_TTL: "86400"
  LOG_LEVEL: "INFO"
  JWT_EXPIRATION_MS: "86400000"
