apiVersion: v1
kind: ConfigMap
metadata:
  name: physical-config
  namespace: physical
data:
  NACOS_SERVER_ADDR: "nacos-service:8848"
  NACOS_NAMESPACE: "physical"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  MYSQL_HOST: "mysql-service"
  MYSQL_PORT: "3306"
  KAFKA_SERVERS: "kafka-service:9092"
  SENTINEL_DASHBOARD: "sentinel-service:8080"
