apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-svc-config
  namespace: ilbuy-l5
  labels:
    app: gateway-svc
    layer: l5
    env: production
# prod replicas_hint: 2
data:
  ENV: "production"
  SERVER_PORT: "8010"
  REDIS_HOST: "redis.ilbuy-infra.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  LOG_LEVEL: "INFO"
  JWT_EXPIRATION_MS: "86400000"
  JAVA_OPTS: "-Xms256m -Xmx512m"
