apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-svc-config
  namespace: ilbuy-l5
  labels:
    app: gateway-svc
    layer: l5
    env: development
data:
  ENV: "development"
  SERVER_PORT: "8010"
  REDIS_HOST: "localhost"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  LOG_LEVEL: "DEBUG"
  JWT_EXPIRATION_MS: "86400000"
  JAVA_OPTS: "-Xms128m -Xmx256m"
