---
apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
  namespace: ilbuy-l5
  labels:
    app: gateway-svc
    layer: l5
spec:
  type: NodePort
  selector:
    app: gateway-svc
  ports:
    - port: 8010
      targetPort: 8010
      nodePort: 30010
      name: http

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway-svc
  namespace: ilbuy-l5
