apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: ilbuy
  labels:
    app: api-gateway
    layer: l1-gateway
spec:
  type: LoadBalancer          # 生产环境使用 LoadBalancer；本地测试改为 NodePort
  selector:
    app: api-gateway
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
