---
apiVersion: v1
kind: Service
metadata:
  name: user-svc
  namespace: ilbuy-l5
  labels:
    app: user-svc
    layer: l5
spec:
  type: ClusterIP
  selector:
    app: user-svc
  ports:
    - port: 8020
      targetPort: 8020
      name: http

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-svc
  namespace: ilbuy-l5
