---
apiVersion: v1
kind: Service
metadata:
  name: order-svc
  namespace: ilbuy-l5
  labels:
    app: order-svc
    layer: l5
spec:
  type: ClusterIP
  selector:
    app: order-svc
  ports:
    - port: 8022
      targetPort: 8022
      name: http

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-svc
  namespace: ilbuy-l5
