apiVersion: v1
kind: Service
metadata:
  name: physical-urine
  namespace: physical-health
spec:
  type: ClusterIP
  selector:
    app: physical-urine
  ports:
    - name: http
      port: 9010
      targetPort: 9010
