apiVersion: v1
kind: Secret
metadata:
  name: ilbuy-l5-secrets
  namespace: ilbuy-l5
type: Opaque
stringData:
  DB_USER: "ilbuy"
  DB_PASS: "CHANGE_ME"
  REDIS_PASS: ""
  JWT_SECRET: "CHANGE_ME_AT_LEAST_32_CHARS_LONG"
  RABBIT_USER: "ilbuy"
  RABBIT_PASS: "CHANGE_ME"
