---
apiVersion: v1
kind: Service
metadata:
  name: recommend-svc
  namespace: ilbuy-l5
  labels:
    app: recommend-svc
    layer: l5
spec:
  type: ClusterIP
  selector:
    app: recommend-svc
  ports:
    - port: 8032
      targetPort: 8032
      name: http

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: recommend-svc
  namespace: ilbuy-l5
