apiVersion: v1
kind: ConfigMap
metadata:
  name: product-svc-config
  namespace: ilbuy-l5
  labels:
    app: product-svc
    layer: l5
    env: development
data:
  ENV: "development"
  SERVER_PORT: "8021"
  DB_HOST: "localhost"
  DB_PORT: "3306"
  DB_NAME: "ilbuy_product"
  DB_URL: "jdbc:mysql://localhost:3306/ilbuy_product?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC"
  REDIS_HOST: "localhost"
  REDIS_PORT: "6379"
  REDIS_DB: "2"
  ES_HOST: "http://localhost:9200"
  LOG_LEVEL: "DEBUG"
  JWT_EXPIRATION_MS: "86400000"
  JAVA_OPTS: "-Xms256m -Xmx512m"
