---
apiVersion: v1
kind: Service
metadata:
  name: product-svc
  namespace: ilbuy-l5
  labels:
    app: product-svc
    layer: l5
spec:
  type: ClusterIP
  selector:
    app: product-svc
  ports:
    - port: 8021
      targetPort: 8021
      name: http

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: product-svc
  namespace: ilbuy-l5
